apiVersion: v1
kind: Service
metadata:
  name: halifax-incident-response-service
spec:
  selector:
    app: halifax-incident-response
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
  type: LoadBalancer
